services:
  - type: web
    name: mindease-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FIREBASE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
