services:
  - type: web
    name: mindease-chatbot
  - type: web
    runtime: python
    pythonVersion: 3.11.7
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FIREBASE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
